### PR TITLE
Moved index.html to markdown.

### PR DESCRIPTION
**Pull request by gryf**
Also, introducing _layouts

### CODE REVIEW

**Comment by d-torrance** [comment]
Thanks for the pull request!  However, `index.html` (and most of the site) is already in Markdown in the `source` branch.

I never got Travis working after we made those rst updates last summer, so for now updates have pretty ugly -- run jekyll on the `source` branch locally, then copy the generated html files to `master`.

**Comment by gryf** [comment]
Wait. This is really wrong. I remember, that I convert most of the html files to md/rest. Why I see html generated files again?

**Comment by gryf** [comment]
Hm. Let me double check on my clone, but I'm pretty sure it was working as expected.

My setup was like almost canonical github pages example - on repository on `master` branch there was sources, and on `gh-pages` there was generated site pushed on every commit pushed to master.

**Comment by d-torrance** [comment]
It may be as simple as the difference between an organization site and a project site.  This an organization site, which uses `master`, whereas your clone would be a project, which uses `gh-pages`.

https://help.github.com/en/github/working-with-github-pages/about-github-pages#publishing-sources-for-github-pages-sites

**Comment by gryf** [comment]
Oh, you're right about the branch - it has to be `master` in case of organizations and users. Sorry for the noise.
As for the build, it seems to work correctly (besides absolute links): https://gryf.github.io/wmaker_page/ (so the repo is https://github.com/gryf/wmaker_page) , it was done on fresh repo with reST - you can check generated files on `gh-pages` branch. Perhaps it is as easy as to change it to `master` in `.travis.yml` to make it work.

**Comment by d-torrance** [comment]
Yay, got it working -- thanks for all your help!

**Comment by gryf** [comment]
\o/ you're welcome :)

**Pull request closed without merging**
