### PR TITLE
Changed url for download.

### PR DESCRIPTION
**Pull request by gryf**
Since we already have official GH mirror of the code repository, releases can be get from there. No need to clutter homepage repository with binaries anymore.

### CODE REVIEW

**Comment by d-torrance** [comment]
I think we should stick with the same tarballs that are currently distributed, which are built with `make dist` and include nice things like a `configure` script that wouldn't exist in the `git archive` versions that Github creates.  Also, Debian packaging tools would complain if you tried to build a 0.95.9 package using the Github tarball since the checksums don't match with the current tarball in the Debian archive.

I did go ahead and upload the two that currently live in the git repository to the [releases](https://github.com/window-maker/wmaker/releases) page, and I think it's a great idea to link to them there.  However, I think we should probably keep the tarballs at the old spot for a while to avoid broken links, e.g., the [Arch package page](https://aur.archlinux.org/packages/windowmaker/) links directly to the current tarball url.

What do you think?

**Comment by gryf** [comment]
Well, that's reasonable. I thought, that it is enough for building wmaker. But the checksum here is a vital point.

Also, if we speak about different distributions - what do you think of removing debian directory from the sources? I mean, this shouldn't be on the wmaker team, I'd rather expect that all distribution related things would be maintained by the appropriate people for every distribution.

**Comment by d-torrance** [comment]
Yeah, I'm not sure why it was included in the first place.  I suppose for users to build their own Debian packages?  But now they could fetch Debian's packaging branch from [Salsa](https://salsa.debian.org/wmaker-team/wmaker), or even the [branch I've set up for building PPA packages from next](https://github.com/d-torrance/wmaker/tree/ppa).

I've always submitted Debian's changes back upstream (squashed into one commit per package version) to keep it up-to-date and working with the next branch.  But my motivation has been, "If it's going to be there, then it should work" and not "It *should* be there."  I certainly wouldn't be opposed to a patch removing it.

**Comment by gryf** [comment]
Awesome :)

**Pull request closed without merging**
